### ISSUE TITLE
Returning undefined in Middleware Functions does nothing?

### ISSUE THREAD

**Issue by desiprisg** [MichalLytek/type-graphql#1035]
**Describe the Bug**
Returning undefined from middleware after doing ``` await next()``` is like returning the normal result. I am getting the object back. It only works if I return null(when I do indeed get back null from graphql).

**Expected Behavior**
Maybe this is supposed to happen because of how graphql works(and how middleware is designed)? I'm not that deep into graphql yet so sorry if it's not a bug after all but if it isn't, it might be useful to mention this in the docs.

**Comment by MichalLytek** [comment]
Yes, returning undefined is like returning no value:
https://github.com/MichalLytek/type-graphql/blob/094654a64f7f59e5d5e832150d51fa164125b56a/src/resolvers/helpers.ts#L113-L117

It works like that because the `await next()` approach that is frequently used could cause swallowing resolvers values.

For GraphQL runtime null and undefined are the same, so you can safely return `null` from the middleware.

**Comment by desiprisg** [comment]
Thanks for the quick response. Makes sense.
