### ISSUE TITLE
All query and mutations must be decorated with `Authorized`

### ISSUE THREAD

**Issue by higgins** [MichalLytek/type-graphql#1234]
**Is your feature request related to a problem? Please describe.**
We'd like every `@Query` and `@Mutation` to require `@Authorized` decorator. We want every operation we expose in our graphql to go through our authChecker.

**Describe the solution you'd like**
If we provide `operationsMustBeAuthorized` to `buildSchema`, we throw an error if any query or mutation in the provided resolvers isn't decorated with `Authorized` decorator.

**Describe alternatives you've considered**
Write a custom linter to require all methods in a resolver class to have the `Authorized` decorator

**Additional context**
N/A

**Comment by MichalLytek** [comment]
Create your own global middleware with your custom auth logic.

The built-in auth checker was always designed with simplicity and base usage scenario in mind.
It can't be complex and support plenty of different modes.
With extensions and middlewares you can build it by yourself.

**Comment by higgins** [comment]
> Create your own global middleware with your custom auth logic.

Thanks, we'll go that route! Closing

**Comment by chadacious** [comment]
Using a global middleware "works", but I was surprised to find that the global middleware iterates not just over declared Queries, Mutations and their requested props, but all of the props of the response! Including nested arrays of objects. The performance of this seems terrible/unusable for even moderately sized responses.

I feel like I must be missing something, but shouldn't we have a way to ask the global middleware to "not" iterate the entire response object? For example, if I slightly modify the `createBasicFieldResolver` to do something like this:
```
        const justQueryAndMutation = ["Query", "Mutation"].includes(info.path?.typename || "") ? middlewares : [];
        return helpers_1.applyMiddlewares(container, resolverData, justQueryAndMutation, () => root[fieldMetadata.name]);
```
The global middleware is called just for query and mutation declarations and I get what I am looking for. But otherwise, the CPU spins up and fans start blowing as it iterates over the entire response calling my middlware function for no purpose. 

I realize there could be some use cases where this would be desirable, but definitely not in my case. So I'm looking for some way to create my own basic field resolver, or maybe extend buildSchema with my own queryAndMutationMiddlewares config... hmm.

**Comment by chadacious** [comment]
So for now, I've hooked the applyMiddlewares function so I can do what I want in this case. Not sure I recommend this in general but at least it works in my use case:
```
import { applyMiddlewares } from "type-graphql/dist/resolvers/helpers";

...

const originalApplyMiddlewares = applyMiddlewares;
    (applyMiddlewares as any) = function (container: IOCContainer,
        resolverData: ResolverData<any>,
        middlewares: Array<Middleware<any>>,
        resolverHandlerFunction: () => any): Promise<any> {
        const justQueryAndMutation = ["Query", "Mutation"].includes(resolverData?.info.path?.typename || "") ? middlewares : [];
        return originalApplyMiddlewares(container, resolverData, justQueryAndMutation, resolverHandlerFunction);
    };
```

Now I should be able to use graphql-sheild, or other globalMiddlewars, without the performance drain of unreasonable recursive traversing of the response props.
