### ISSUE TITLE
`defaultValue` array conflicts with initializer

### ISSUE THREAD

**Issue by carlocorradini** [MichalLytek/type-graphql#1364]
**Describe the Bug**

Given a simple `InputType` class:
```ts
@InputType()
export class CreateUserInput {
  @Field(() => [Roles], { defaultValue: [Roles.SIMPLE] })
  roles: Roles[] = [Roles.SIMPLE];
}
```
When using array as default(s), `defaultValue` conflicts with initializer even though they are the same value.

**To Reproduce**
Repository example: <https://github.com/carlocorradini/typegraphql_default_value>

**Expected Behavior**
Execute without any particular problem, as it is the same as when using non-array default value(s).

**Logs**
`The 'roles' field of 'CreateUserInput' has conflicting default values. Default value from decorator ('SIMPLE') is not equal to the property initializer value ('SIMPLE').`

**Environment (please complete the following information):**

- OS: Windows
- Node: 16.14.2
- Package version: 1.1.1 (tried also in 1.2.0-rc.1)
- TypeScript version: 4.8.4

**Comment by MichalLytek** [comment]
It happens because of that check:
https://github.com/MichalLytek/type-graphql/blob/e8e164d8324a06fe0906ea896413ceccc6cf9cea/src/schema/schema-generator.ts#L170-L181

It's just a guard - technically, you should have been using only one approach: either `defaultValue` option or field initializer.
Also, as a workaround, assign the array to a `const` value and use it there.

I'm not sure if adding a dedicated check for arrays makes sense in that case.

**Comment by carlocorradini** [comment]
Ok perfect, going for `defaultValue`
