### ISSUE TITLE
TypeDoc

### ISSUE THREAD

**Issue by carlocorradini** [MichalLytek/type-graphql#1612]
**Is your feature request related to a problem? Please describe.**
Add [`TypeDoc`](https://typedoc.org) to help exploring the API, and much more...
The generated documentation can be included in the website 🥳

**Additional context**
I've already created a branch with TypeDoc. See https://github.com/carlocorradini/type-graphql/tree/typedoc and run `npm run gen:typedoc`

**Comment by MichalLytek** [comment]
I don't see a point of this in that shape. It's just a DTS browser that you have to change your window from vscode to browser in order to see that. Jumping in IDE is much easier.

Without JSDoc, proper documentation and link (#17) it does not bring the needed value. We can use it when #17 is ready and it can integrate with that easily.

**Comment by carlocorradini** [comment]
LGTM
Future! 🔮
