### ISSUE TITLE
Idea: class-validator -> directive

### ISSUE THREAD

**Issue by j** [MichalLytek/type-graphql#322]
I know directives aren't supported yet, but one sucky thing I've noticed is when you use class-validators and the front-end passes invalid data that fails for graphql input validation + class-validation errors, you'll get the graphql error first, then re-submit and get the class-validation error.

What would be cool is that if/when directives get supported, that the following could happen:

```typescript
class Post {
  @Length(3, 50)
  @Field()
  title: string;
}
```

Would generate something like:
```graphql
type Post {
  name: String! @ValidLength(3, 50)
}
```
Obviously, this is #goals, but just having directives would be a one up.

Even this would be cool:

```typescript
class Post {
  @Field({ directives: "@constraint(minLength: 3, maxLength: 50)" })
  title: string;
}
```

And potentially allowing for:

Even this would be cool:

```typescript
import { string, setup } from 'yup-type-graphql';

buildSchema({
  ...,
  directives: [setup()]
})

class Post {
  @Field({ directives: [string().min(3).max(50)] })
  title: string;
}
```

**Comment by 19majkel94** [comment]
> the front-end passes invalid data that fails for graphql input validation + class-validation errors, you'll get the graphql error first, then re-submit and get the class-validation error

That's why you should validate your data first on the client side. And treat server validation only as a security feature for those who tries to call your mutations/queries manually.

> I know directives aren't supported yet

I'm not sure if directives are evaluated just in time of validating the query against schema. Maybe you think about custom scalars?

> yup-type-graphql

Yeah, I will provide integration for common libs and patterns + building blocks for making a custom ones. For now, `class-validator` support is hardcoded but with field metadata #124 and custom decorators #45 or middlewares, it's easy to provide this kind of integrations without relying on directives.

**Comment by MichalLytek** [comment]
> Even this would be cool:
> ```ts
> class Post {
>   @Field({ directives: "@constraint(minLength: 3, maxLength: 50)" })
>   title: string;
> }
> ```

It's supported by #369 

> Even this would be cool:
> ```ts
> import { string, setup } from 'yup-type-graphql';
> 
> buildSchema({
>   // ...,
>   directives: [setup()]
> })
> 
> class Post {
>   @Field({ directives: [string().min(3).max(50)] })
>   title: string;
> }

Agree but can be done by external libs like in this snippet.
You need to create standard GraphQL directives which are translated to class-validator or yup validation during directives execution.

There won't be any special built-in feature for that like for `class-validator`.

So closing this one 🔒
