### ISSUE TITLE
Can't modify @Root value if @Arg is present

### ISSUE THREAD

**Issue by angelvega93** [MichalLytek/type-graphql#458]
**Describe the bug**
Can't modify @Root (parent) value in a field resolver if @Arg is present in the function.

**Enviorment:**
 - OS: Windows & Ubuntu 18.04
 - Node v12.10.0
 - Package version 0.17.5
 - TypeScript version 3.6.3

**Additional context**
Here is a repo where you can find the issue:
https://github.com/angelvega93/graphql-field-resolver-bug

**Comment by MichalLytek** [comment]
How do you check if you have "modified" or not the root value?

Do you know that the field resolvers are executed in parallel so if you modify it in one field resolver, it might be modified or not in the second one, depending on the execution order and other async stuff?

**Comment by MichalLytek** [comment]
I've added a test case for that using middlewares and the root object is properly modified.

I bet that you were trying to overwrite the field in another field resolver and because it was read by GraphQL runtime earlier, the value returned to client is the old one, not modified. The one with args goes through async transform and validate pipeline which takes some time, that's why it reads the `has_next` original value.

You should create a field resolver for that field and use root object to read the current value and sometime replace it with your own depending on the business requirements.
