### ISSUE TITLE
Generic Types seems not working in circular case

### ISSUE THREAD

**Issue by pd4d10** [MichalLytek/type-graphql#504]
**To Reproduce**

Type `User` has circular dependencies, so we split them into two files to avoid [class hoisting problem](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Hoisting)

```ts
// user.ts
@ObjectType()
export class User {
  @Field(_ => FollowingConnection) following: FollowingConnection;
}
```
```ts
// connection.ts
export function ConnectionResponse<TItem>(TItemClass: ClassType<TItem>) {
  @ObjectType({ isAbstract: true })
  abstract class ConnectionResponseClass {
    @Field(_ => Int) totalCount: number;
    @Field(_ => [TItemClass]) nodes: TItem[];
  }
  return ConnectionResponseClass;
}

@ObjectType()
export class FollowingConnection extends ConnectionResponse(User) {}
```

**Expected behavior**
It should work according to [the documentation](https://typegraphql.ml/docs/generic-types.html), but instead throw an error:

```sh
Error: Cannot determine GraphQL output type for nodes
```

**Enviorment (please complete the following information):**
 - OS: macOS
 - Node: v12.14.0
 - Package version: v0.17.5 (latest)
 - TypeScript version: v3.7.4

**Comment by MichalLytek** [comment]
`User` class needs `FollowingConnection` class but it's a class factory, not a static class.
So it needs a correct value at evaluation time (executing the factory), that's why you have to use the same trick like `@Field(type => Foo)` does - deferring collecting the type value until all circular deps are settled.

So in your case the `ConnectionResponse` generic types factory has to accept not a concrete value, but a deffered function:
```ts
export function ConnectionResponse<TItem>(getNodesType: () => [ClassType<TItem>]) {}
```

Then you can just put it into the `@Field` decorator options:
```ts
 @Field(getNodesType)
 nodes: TItem[];
```

And execute the factory with deffered value to create a `FollowingConnection`:
```ts
export class FollowingConnection extends ConnectionResponse(() => [User]) {}
```

**Comment by pd4d10** [comment]
Thanks!

**Comment by khiner** [comment]
This helped me too, thank you!
