### ISSUE TITLE
Integration with Knexjs

### ISSUE THREAD

**Issue by canhkieu** [MichalLytek/type-graphql#518]
I think knexjs is the best choice for working with database. Could you make integrate with Knexjs or make an simple example like TypeORM.

**Comment by MichalLytek** [comment]
What is not working for you and how do you see the integration?

**Comment by glen-84** [comment]
TypeGraphQL doesn't force you to use a specific database library like TypeORM, and I doubt that Michał has the time to write sample code for every library available.

**Comment by patricklol22** [comment]
I use knex+Objection in TypeGraphQL. You can annotate the model classes as described in TypeGraphQL the documentation. Works without issues so far.

**Comment by MichalLytek** [comment]
> Works without issues so far.

So nothing to document. We have a showcase for TypeORM and Typegoose because they need lazy (promises) fields or transform middleware. If you think that somebody new won't be able to integrate Objection.js with TypeGraphQL, please create an example repository and write a blog post on Medium or Dev.to about that 😉
