### ISSUE TITLE
How to omit fields from JSON.stringify output?

### ISSUE THREAD

**Issue by kevzettler** [MichalLytek/type-graphql#524]
When we serialize the raw typescript entity object this doesn't respect the various field annotations in our GQL entities and ends up leaking unwanted data. Example below a Profile entity class

```
import { Field, Int, ObjectType } from 'type-graphql'
import { Column, Entity, ManyToOne, OneToMany } from 'typeorm'
import { Account } from '../account/account.entity'

export class Profile {
  @Field()
  @Column({ unique: true })
  public username: string

  @Field()
  @Column()
  public name: string

  // Relations

  @Column()
  public accountId: string

  @ManyToOne(type => Account, account => account.profiles, { eager: true })
  public account: Account
}
```

`account` has sensitive data. When we `JSON.stringify` a Profile reference we don't want account  output. Account is not annotated with `@Field` and we expect it would not be output.

**Comment by MichalLytek** [comment]
I don't understand what your issue is about 😕 

Why your `Profile` class has `@Field()` annotations without `@ObjectType` decorator?

Please show me:
1) Generated GraphQL schema SDL
2) The query you are executing that ends up with leaking unwanted data
3) The resolver class code for this query
4) The places in code where you use `JSON.stringify`
