### ISSUE TITLE
@ArgsType not working after importing from locally linked package

### ISSUE THREAD

**Issue by akash-rajput** [MichalLytek/type-graphql#526]
**Describe the bug**
classes defined @ArgsType annotation do not seem to work when imported from a locally linked package. The target & lib are set to as per instructions in docs for both packages
It throws an error `Cannot determine output type for xyz`

**To Reproduce**
Create a package & link it locally with npm link. 
**Expected behavior**
Imports for ArgsType should work out of the box.

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.

**Enviorment (please complete the following information):**
 - OS: OSX Mojave
 - Node (e.g. 12.0.1)
 - Package version [0.17.5] (please check if the bug still exist in newest release)
 - TypeScript version (3.6.4)

**Additional context**
NA

**Comment by MichalLytek** [comment]
> It throws an error Cannot determine output type for xyz

As stated in the template:

![image](https://user-images.githubusercontent.com/10618781/72794378-35690200-3c3c-11ea-92cc-ce9b577b3cae.png)

Please paste the whole error and the part of code it refers to.

I think that the problem is about using scalars like `Int`, `Float` or `ID`. TypeGraphQL has shared global metadata storage. `graphql-js` should be a peer dependency which means you can't use npm link while having multiple node_modules.

We have 2020 now, maybe it's time to stop using broken `npm link` feature and move on to lerna with deps hoisting? Or at least replace npm link with https://github.com/mweststrate/relative-deps.

**Comment by akash-rajput** [comment]
Anyways, Got it working with a fresh `npm i` & relinking. Thanks.

**Comment by MichalLytek** [comment]
Fresh `npm install` is doing deps deduplication, so you have single instance of `graphql-js` in `node_modules` 😉
