### ISSUE TITLE
How to custom the auth-checker error message?

### ISSUE THREAD

**Issue by Vbubblery** [MichalLytek/type-graphql#562]
Hello,

By default, the error message of auth checker is:
```javascript
{
  "error": {
    "errors": [
      {
        "message": "Context creation failed: Request failed with status code 401",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "Error: Context creation failed: Request failed with status code 401",
              "    at /Users/junchengzhou/Flowlity/orders_manager/src/server.ts:30:17",
              "    at processTicksAndRejections (internal/process/task_queues.js:94:5)"
            ]
          }
        }
      }
    ]
  }
}
```

But I want to custom the error message, make it easy to deal with.

I checked docs and example. No clue :(

**Comment by MichalLytek** [comment]
You can run `examples/authorization` to see the auth feature in action.
It returns this:
```json
{
  "errors": [
    {
      "message": "Access denied! You don't have permission for this action!",
      "locations": [
        {
          "line": 24,
          "column": 5
        }
      ],
      "path": [
        "recipes",
        0,
        "ratings"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Access denied! You don't have permission for this action!",
            "    at AuthMiddleware (d:\\Projekty\\type-graphql\\src\\helpers\\auth-middleware.ts:16:62)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

So your error and stack trace shows that you capture and transform the error somewhere else, so it's not `type-graphql` fault.

In Apollo Server, you can use `formatError` option to capture and change/transform the error returned to client.

**Comment by toniopelo** [comment]
Hi @MichalLytek,

How should we do when we want a different error depending on the resolver or the authorization requirements ?
Example: I do have an auth-checker function concerning email validation being done, I do not want to have the same error message as when you're not admin. Relying on ApolloServer or a middleware down the chain would be difficult because I won't known why the auth checker did reject the request at this point.

If auth-checker would be able to throw an error that would replace the default one, this would allow to do exactly that don't you think ? (and non-breaking change I think ?).
In addition to that, the @Authorize(...) decorator could override the error be specifying an error message or something to have a per-resolver granularity.

**Comment by MichalLytek** [comment]
@toniopelo Every custom behavior should be done via custom middleware throwing custom error. Default auth layer is just a basic simple implementation for beginners, not a customizable production-ready solution.

**Comment by toniopelo** [comment]
@MichalLytek Hmm, well that feels odd to me to use custom middlewares when there is a first-class support for this use case.

As perfectly stated in your doc : 
>In express.js (and other Node.js frameworks) we use middleware for this, like passport.js or the custom ones. However, in GraphQL's resolver architecture we don't have middleware so we have to imperatively call the auth checking function and manually pass context data to each resolver, which might be a bit tedious.
\
That's why authorization is a first-class feature in TypeGraphQL!

That doesn't feel like a `simple implementation for beginners, not a customizable production-ready solution`.

To be clear, would you refuse a PR trying to improve the auth-checker errors and granularity because it's not in the project philosophy ? If so I think it should be clearly stated in the docs that this is NOT a fine-grained authorization solution and that we should instead use our own middlewares for better error handling.
Else if you think it would be a good addition, I might try to draft a PR someday.

(Written language can seem aggressive sometimes, to be clear I'm not fighting against you here)

**Comment by MichalLytek** [comment]
> As perfectly stated in your doc :

In pure GraphQL we do not have built-in middlewares. We do have custom plugins for `graphql.js`.
TypeGraphQL authorization feature was created before TypeGraphQL middlewares, hence the docs is written as it is.

> would you refuse a PR trying to improve the auth-checker errors and granularity 

Yes, however you can create a PR with improvement for that section of authorization feature docs and write something that it's a common feature so it has basic support built-in but in complex cases/requirements you can use your own middlewares and decorators to customize it further.

**Comment by matheusbn** [comment]
@Vbubblery You can just throw a different error in the auth checker instead of returning `false`.
