### ISSUE TITLE
Field name argument doesn't work with interface types

### ISSUE THREAD

**Issue by travigd** [MichalLytek/type-graphql#566]
**Describe the bug**
```ts
@InterfaceType
abstract class Animal {
  @Field(() => String, { name: "animalName" })
  abstract getAnimalName: () => Promise<string>;
}

@ObjectType({ implements: [Animal] })
export class Dog {
  async getAnimalName() { return "Fido"; }
  /* ... */
}
```

The generated schema is along the lines of
```graphql
interface Animal {
  animalName: String!
}
```
but if you try to query, you get a GraphQL error along the lines of
```
Error: Cannot return null for non-nullable field Dog.animalName
```
seemingly because the mapping from `animalName` to `getAnimalName` hasn't happened.

**Addendum:**
I see that `name` isn't supported in some other places (#263) but this doesn't seem like the same situation.

**Comment by MichalLytek** [comment]
As stated in #263, the name option in decorator was introduced only for making resolvers inheritance possible:
https://typegraphql.ml/docs/interfaces-and-inheritance.html#resolvers-inheritance

The rest is just a side effect of my internal refactor when I started using `schemaName`. It work for output type because of the way the `graphql-js` resolves the fields but not for the input types.

So I agree, from the user perspective if it works for object types, it should work for object implementing interface and should be "fixed" 😉

**Comment by travigd** [comment]
@MichalLytek I have a PR open for this. Not sure if you missed it. It's a pretty simple change. :^)
