### ISSUE TITLE
Docs site is not working (new domain)

### ISSUE THREAD

**Issue by MichalLytek** [MichalLytek/type-graphql#572]
## Update

The website is now live under a new domain 🎉

**https://typegraphql.com/**

This is the last domain change I hope 😄 

### Background

The `typegraphql.ml` domain from [Freenom](https://www.freenom.com/en/index.html?lang=en) has expired (or cancelled because I had no reminder on email as usual!), so the docs site is not reachable by this URL.

Freenom has marked typegraphql.ml as a "special domain" with high interest and now demand euros for it 🙄 
> A SPECIAL DOMAIN IS A DOMAIN THAT CAN ONLY BE REGISTERED FOR A FEE, BECAUSE THE DOMAIN IS SHORT OR CONTAINS A MEANINGFUL DICTIONARY WORD. SPECIAL DOMAINS ARE OF GREAT VALUE!

**Comment by rfgamaral** [comment]
I would recommend you buy the domain from Cloudflare instead, it's cheaper.

**Comment by MichalLytek** [comment]
@rfgamaral Thanks for the tip! However, looks like Cloudflare doesn't allow buying domains, only transferring them 😕

**Comment by rfgamaral** [comment]
@MichalLytek I like Cloudflare because of everything else they offer for free and I like to pair those services with a domain (ever since they started providing that service). If you don't need/care for those services, maybe look at [Porkbun](https://porkbun.com/checkout/search?q=typegraphql.com) instead.

I've used Porkbun before and they are cheap (`typegraphql.com`, $3.90 / first year, renews at $8.56), they are nice and have a simple/easy domain management (from my point of view, of course). After 60 days you can transfer it to Cloudflare if you want and the annual price will be slightly cheaper (a few cents).

**Comment by rbeer** [comment]
fyi: The search is still pointing at the domain.

**Comment by MichalLytek** [comment]
The website is now live on http://typegraphql.com/ 🎉 

It may require up to 24h to propagate the DNS and to enable HTTPS for github pages.
In the meantime you can run `nslookup /flush` and it should work immediately 💪

**Comment by MichalLytek** [comment]
I also wonder if I should buy the `typegraphql.ml` domain and set redirection to the new `.com` one - please 👍 or 👎 this post 😄

**Comment by rfgamaral** [comment]
I'd say to let SEO do it's job... Unless the `.ml` domain is not that expensive, maybe buy it for a single year?

**Comment by waynevanson** [comment]
There are so many links to typegraqph.ml in the docs, might worth chucking a regex through it and change them all at once?

**Comment by MichalLytek** [comment]
@waynevanson Where do you have some links to `.ml` in the docs? 🧐

**Comment by waynevanson** [comment]
Sorry @MichalLytek, looks like I was going through my history instead of the docs 😳

**Comment by MichalLytek** [comment]
Closing as Google is now indexing TypeGraphQL properly 😉
