### ISSUE TITLE
Int scalar not working: Cannot determine GraphQL output type for id

### ISSUE THREAD

**Issue by webnoob** [MichalLytek/type-graphql#614]
**Describe the Bug**
Given this model:
```
import { Field, Int, ObjectType } from 'type-graphql'

@ObjectType()
export class PenNameDto {
  @Field(type => Int, { nullable: true })
  id?: number
}
```

I get `UnhandledPromiseRejectionWarning: Error: Cannot determine GraphQL output type for id`

If I remove `type => Int` then it works and generates the schema.

**To Reproduce**
Not too sure. I have this model in a sub project that I'm packaging and then import into my client and API code (shared code). I then import the model into my API to use.

Declaring this model in my API (which I'm currently doing) works as expected but I'm trying to move the code to use shared models.

**Expected Behavior**
The scalar to work

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.

**Environment (please complete the following information):**

- OS: [Windows]
- Node (e.g. 12.13.0)
- Package version [e.g. 0.17.6] (please check if the bug still exist in newest release)
- TypeScript version (e.g. 3.3.3)

**Additional Context**
I'm not expecting there to be a bug here, I'd just like some guidance on where to debug this as it's clearly working in my API but not when I import the model from my shared package.

**Comment by MichalLytek** [comment]
> Not too sure. I have this model in a sub project that I'm packaging and then import into my client and API code (shared code). I then import the model into my API to use.

>  it's clearly working in my API but not when I import the model from my shared package.

Kinda duplicate of #381.

You need to make `graphql-js` a peer dependency of your shared package. Then it will use the same package instance as your main app.

If the problem encounters during development, you need to use lerna or other monorepo with deps hoisting.

**Comment by webnoob** [comment]
Funny, I was leaning towards this as well so I've just been getting yarn workspaces setup so assume that'll fix it.

**Comment by Druux** [comment]
@MichalLytek Do you know an alternative way to the monorepo proposal to access an external model during development? My model is based on Typescript, so I have no way to specify `graphql-js` as peerDependency, otherwise build-errors would occur. I have already tried several variants, e.g. `relative-deps`, `npm i <local-package>` etc. But I cannot find a way to tell my model to access node_modules of the parent. Monorepos are unfortunately out of the question for me.

**Comment by MichalLytek** [comment]
For developing multiple packages that works as a single unit, only monorepo (lerna or yarn workspaces with hoisting dependencies) are the right solution.

Using peer deps means using dev deps for development which results in node_modules issue. If you don't need monorepo, you can just use private npm registry like verdacio and publish the package there and then install it in another project so it gonna use local node_modules.

**Comment by theseyi** [comment]
@webnoob what configuration worked for you?

I've got a repo using Yarn 2 Workspaces, but with `nodeLinker: node-modules`, so not using pnp. In my client / graphql server, I have `graphql` as a dependency. However, in my shared package I have `graphql` as a peer dependency. I also have configured yarn in the shared package with have `hoistingLimits: workspaces` which implies that the package is not hoisted past the workspace itself, in this case the shared package. Had to set this because `type-graphql` is also a dependency in the shared package.

However, I'm still getting `Error: Cannot determine GraphQL output type for 'id'`
