### ISSUE TITLE
InputType class constructor called without arguments

### ISSUE THREAD

**Issue by alextpr** [MichalLytek/type-graphql#644]
Thank you @MichalLytek for the fantastic library!

**Is your feature request related to a problem? Please describe.**
I am finding that TypeGraphQL wants to be able to construct an example instance of each input type with no constructor parameters during initialisation, specifically `inputInstance` here in buildTypesInfo():

```ts
this.inputTypesInfo =
  getMetadataStorage().inputTypes.map<InputObjectTypeInfo>(inputType => {
  ...
  const inputInstance = new (inputType.target as any)();
  return { ... }
});
```

It seems like this is done in order to determine default values for optional fields.

I would ideally like to keep my constructors as restrictively/accurately typed as possible, and in many cases there are no possible default values that would actually be valid for the data I'm working with. I don't really want to define constructors that accept no input in these cases.

**Describe alternatives you've considered**
I've been using the following as a workaround:

```ts
@InputType
class Example {
  @Field(type => Number) requiredData: number;

  constructor(requiredData: number) {
    if (requiredData === undefined) {
      // Workaround for TypeGraphQL
      this.requiredData = undefined as unknown as number;
    } else {
      this.requiredData = requiredData;
    }
  }
};
```

This seems fairly suboptimal, however, and results in a lot of extra code on every input type.

**Describe the solution you'd like**
Would there be any better workarounds here, or would it be possible for TypeGraphQL to skip creation of the `inputInstance` in cases where it is not strictly necessary?

I see that there's a `defaultValue` option for `@Field`, so it would seem like if all fields are either non-nullable or have explicit default values, then it should not be necessary to create the inputInstance.

Thanks!

**Comment by MichalLytek** [comment]
`@InputType` and `@ObjectType` classes are treated like a DTO, dummy object, so they shouldn't have any constructor with some logic attached because TypeGraphQL is not aware of your rules of required data.

Instances are created not only while determining default values but also in runtime to convert input type values to class instances to make `class-validator` work.

So no, unfortunately you can't have constructors in input types, you need to change to the factory pattern instead and have a static method or separate factory class that gonna validate the parameters and construct proper instance.

And reusing this input type DTO inside your code (calling `new Example(requiredData)`) is I believe violating single responsibility principle as you are reusing the infrastructure-layer class somewhere in your model.

**Comment by alextpr** [comment]
Ah I see, thank you. I had yet to look into details on exactly how the class instances were constructed but that makes sense also.

As a newcomer to GraphQL in general, it's quite tempting to look at TypeGraphQL as a way to generate one's data transfer infrastructure automatically by annotating application-level classes — at least in simpler cases where the translation is fairly direct.

So that's not an intended use case, due to mixing DTOs and application-level logic? Perhaps a word of warning in the docs would be useful for those coming from a similar background as myself.

I will certainly consider the single responsibility/separation of concerns implications of my design further as well, thank you.

**Comment by MichalLytek** [comment]
If you want to translate/map the data from app level to the infra (object type) level, you should use separate services (classes) for that, or at least a static method like `MyAppModel.fromInputType(input)` and `MyObjectType.fromAppModel(model)`. This way you do not couple the layers, that indeed might be similar in the very begging of the development but then starts to limit and complicate your codebase.

Technically I can create an instance of the class without calling the constructor but this doesn't change anything if the instance field is initialized there because then the methods might just reference not existing data.

I definitely should add an info about forbidding the use of constructor into the docs 💪

**Comment by MichalLytek** [comment]
Closing via 683963f 🔒
