### ISSUE TITLE
Missing @Service() decoration in typeorm examples

### ISSUE THREAD

**Issue by idanush** [MichalLytek/type-graphql#775]
Tried to make the typeorm example working as we're working with typeorm and looking to get into graphql. 
After spending a couple of stumped hours and reading most of the docs (especially the section on dependency injection) I eventually figured out the issue is a messing @Service() decorator on the resolvers in the example.

It fixed the issue in my case but since I'm brand new with graphql (and di in Javascript) I wanted to make sure I'm in the right. 
If I am I will try to create a pull request to update the examples

**Comment by MichalLytek** [comment]
> missing `@Service()` decorator on the resolvers in the example

Thanks for the report. It must be related to some new TypeDI version change as previously there was no need for such decorator if the class had other decorator already.

I will update the examples and remove TypeDI from the TypeORM example as it can work with active record

**Comment by idanush** [comment]
I wish I understood it better than I do right now but I'm not comfortable enough with the technology yet.  
Will track this ticket and try the changes. It's a lot to grok
Hopefully, I'll write a readme / better docs when I understand the change.

**Comment by NoNameProvided** [comment]
What is the exact error you are seeing? Do you use `typeorm-typedi-extensions`? Since TypeDI 0.9.0 everything you request from the container needs to be registered first via the `@Service` decorator or `Container.set()`. I believe with the latest `typeorm-typedi-extensions` extension most use-cases should work. (There is still some works to be done on the linked TypeORM issue.)

For your case:
- If you see a `ServiceNotFoundError` for __any of your own classes__, you need to register them first via the `@Service` decorator or `Container.set()`. 
- If you see a `ServiceNotFoundError` for __any of the classes exported by this lib__, then a new version of this lib needs to be released where the classes are registered first via the `@Service` decorator or `Container.set()`. 
- If you see a `ServiceNotFoundError` for __any of the classes exported by this TypeORM__, then it needs to be fixed first in the above linked TypeORM issue.

**Comment by idanush** [comment]
@NoNameProvided  thanks for the update. 
My issue was the first case.  I managed to get over it by adding the `@Service` decorator on my classes.  It just wasn't in the documentation which is why I opened this issue.

**Comment by MichalLytek** [comment]
Fixed by aab8be8 🔒
