### ISSUE TITLE
Caching example no longer works

### ISSUE THREAD

**Issue by clayrisser** [MichalLytek/type-graphql#956]
When I run the cache example, it still runs the resolver every time I execute the query. Should't it be caching?

https://github.com/MichalLytek/type-graphql/tree/master/examples/apollo-cache

**Comment by MichalLytek** [comment]
I've checked again and it's working correctly. 

Logs are printed only on a first call, subsequent requests in 10s (TTL) are served from cache:

![image](https://user-images.githubusercontent.com/10618781/126617786-1dcf3695-1b0c-458a-bcf4-1db38c30eeaa.png)

Did you cloned the repo, installed all deps from lock file and run the examples?
Because in Apollo Server 3 they have recently changed the caching and plugins 🤔

**Comment by clayrisser** [comment]
But you can see that the query ran twice. Maybe I'm not understanding it correctly. Any plans to make it work with Apollo 3?

**Comment by clayrisser** [comment]
I see, I copied the files over and had apollo 3. Just switched to apollo 2 and it works. Thanks!

**Comment by MichalLytek** [comment]
@clayrisser There's no plans for making it work with Apollo 3 because it has nothing to do with TypeGraphQL. You can use middlewares, you can use directive, the rest is about configuring apollo plugins which is the same for nexus, NestJS, `graphql-tools`, etc.
